name: CI pipeline # Action name

on: # Trigger on
  push:
  # only take action when push to the main branch
    branches: [ main ]
  # group of steps run together
jobs: 
  build: # First job
    runs-on: ubuntu-latest # the virtual machine environment
    # set sequential steps to excute 
    steps: 
      - name: Checkout code # step name
        uses: actions/checkout@v5 # # its prebuid git action, download repository code to the virtual machine

      - name: Set up Node.js 
        uses: actions/setup-node@v3 # its prebuid git action, Installs Node.js runtime
        with:
          node-version: 16 # Parameters: Configures it to use Node.js version 16

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm test